import {StyleSheet} from 'react-native';
import {colors} from './colors';

export const commonStyles = StyleSheet.create({
  home_container: {
    flex: 1,
    justifyContent: 'flex-start',
    flexDirection: 'column',
    backgroundColor: '#fff',
    width: '100%',
  },
  deviceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    margin: 8,
    borderRadius: 8,
    backgroundColor: '#ffffff', // Set your background color
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5, // Make the component take up the full width
  },
  deviceTitle: {
    fontSize: 18,
    fontFamily: 'Samim',
    color: '#333', // Set your text color
  },
  search_container: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    paddingHorizontal: 10,
    marginHorizontal: '10%',
    marginVertical: 25,
    width: '80%',
  },
  addButtonContainer: {
    position: 'absolute',
    bottom: 20,
    left: '25%',
    width: '50%',
  },
  connectway_container: {
    flexDirection: 'column',
    justifyContent: 'space-around',
    padding: 50,
    gap: 10,
    marginVertical: 20,
  },
  connectway_button: {
    borderColor: 'darkgoldenrod',
    borderWidth: 2,
    padding: 10,
    borderRadius: 10,
    alignItems: 'center',
    paddingVertical: 25,
    backgroundColor: '#fff',
  },
  connectway_icon: {
    width: 60,
    height: 60,
    resizeMode: 'contain',
  },
  connectway_buttonText: {
    marginTop: 5,
    color: 'darkgoldenrod',
    fontSize: 18,
    fontFamily: 'Samim',
  },
  add_dvc_container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#fff',
  },
  add_dvc_inputContainer: {
    marginBottom: 16,
    width: '100%',
  },
  add_dvc_label: {
    fontSize: 16,
    marginBottom: 8,
    fontFamily: 'Samim',
    color: '#333',
  },
  add_dvc_input: {
    width: '100%',
    height: 50,
    borderColor: 'darkgoldenrod',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    fontSize: 16,
    fontFamily: 'Samim',
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  add_dvc_button: {
    marginTop: 16,
    backgroundColor: '#B8860B20',
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'darkgoldenrod',
  },
  add_dvc_buttonText: {
    color: 'darkgoldenrod',
    fontSize: 16,
    textAlign: 'center',
    fontFamily: 'Samim',
  },
  addButton: {
    backgroundColor: '#B8860B',
    borderWidth: 1,
    borderColor: 'darkgoldenrod', // Set your button background color
    padding: 6,
    borderRadius: 5,
    alignItems: 'center',
    margin: 10,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  syncButton: {
    backgroundColor: '#B8860B20',
    borderWidth: 1,
    borderColor: 'darkgoldenrod', // Set your button background color
    padding: 2,
    borderRadius: 5,
    alignItems: 'center',
    margin: 3,
    flexDirection: 'row', 
    maxHeight: 25,
    justifyContent: 'space-around',
    width: 90,
  },
  burger: {},
  text: {
    fontFamily: 'Samim',
  },
  addButtonText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: "Samim"
  },
  icon: {
    width: 32,
    height: 32,
  },
  icon12: {
    width: 12,
    height: 12,
  },
  input: {
    flex: 1,
    paddingVertical: 8,
    fontFamily: 'Samim',
  },
  button: {
    borderColor: colors.gray,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
    borderRadius: 25,
    backgroundColor: colors.white,
    elevation: 2,
    aspectRatio: 1 / 1,
  },
  search_button: {
    padding: 10,
  },
  iconImage: {
    width: '100%',
    height: '100%',
  },
  iconImageHalf: {
    width: '70%',
    height: '70%',
    resizeMode: 'contain',
  },
  main_parent: {
    flex: 1,
    flexDirection: 'column',
    padding: 25,
    gap: 15,
  },
  main_1: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#aaa',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    flexDirection: 'column',
    padding: 10,
  },
  button_icon: {
    flex: 1,
    maxWidth: '25%',
    padding: 5,
    flexDirection: 'column',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'darkgoldenrod',
    borderRadius: 10,
    aspectRatio: 1 / 1,
    backgroundColor: "#b8860b15"
  },
  button_icon_black: {
    flex: 1,
    maxWidth: '25%',
    paddingTop: 4,
    flexDirection: 'column',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: 10,
    aspectRatio: 1 / 1,
    backgroundColor: "#fff8"
  },
  main_2: {
    flex: 2,
    borderWidth: 1,
    borderColor: '#aaa',
    borderRadius: 10,
    backgroundColor: '#ffffff',
  },
  main_3: {
    flex: .7,
    flexDirection: "row",
    gap: 10,
    alignItems: 'center',
  },
});
